"""
Flood Preparedness Unit — API Routes
====================================
Official REST Endpoints:
    GET  /api/disaster-data/flood          -> Unified CWC/NWIC live flood payload.
    GET  /api/disaster-data/flood/stations -> River water-level stations with ?scope=guntur/ap/india.
    GET  /api/disaster-data/flood/rainfall -> Telemetry rainfall stations.
    GET  /api/disaster-data/flood/forecast -> Official CWC forecasts vs Suraksha Kavach AI projections.
    GET  /api/predict/flood                -> AI flood-risk classification + 14-day discharge forecast.
    POST /api/disaster-data/flood/refresh  -> Manual refresh trigger.
"""

from flask import Blueprint, jsonify, request

from app.utils.flood_data import FloodDataManager
from app.utils.flood_ml import predict_flood

bp = Blueprint("flood_api", __name__, url_prefix="/api")


@bp.route("/disaster-data/flood", methods=["GET"])
def get_flood_data():
    """Return unified real-time CWC/NWIC river water levels, rainfall, forecasts, and status."""
    try:
        force = request.args.get("force") in ("1", "true", "yes")
        payload = FloodDataManager.get_live_flood_payload(force=force)
        return jsonify(payload)
    except Exception as exc:
        return jsonify({"status": "error", "message": str(exc)}), 500


@bp.route("/disaster-data/flood/stations", methods=["GET"])
def get_flood_stations():
    """Return CWC/NWIC river telemetry stations filtered by geographic scope."""
    try:
        scope = request.args.get("scope", "guntur")
        payload = FloodDataManager.get_live_flood_payload()
        all_stations = payload.get("stations", [])
        filtered = FloodDataManager.filter_stations_by_scope(all_stations, scope=scope)
        return jsonify({
            "status": "success",
            "scope": scope,
            "count": len(filtered),
            "stations": filtered,
            "source": "CWC / NWIC Telemetry",
            "observationTimestamp": payload.get("timestamps", {}).get("observationTimestamp")
        })
    except Exception as exc:
        return jsonify({"status": "error", "message": str(exc)}), 500


@bp.route("/disaster-data/flood/rainfall", methods=["GET"])
def get_flood_rainfall():
    """Return CWC/NWIC telemetry hourly rainfall stations filtered by geographic scope."""
    try:
        scope = request.args.get("scope", "guntur")
        payload = FloodDataManager.get_live_flood_payload()
        all_rain = payload.get("rainfallStations", [])
        filtered = FloodDataManager.filter_stations_by_scope(all_rain, scope=scope)
        return jsonify({
            "status": "success",
            "scope": scope,
            "count": len(filtered),
            "rainfallStations": filtered,
            "source": "CWC / NWIC Telemetry",
            "observationTimestamp": payload.get("timestamps", {}).get("observationTimestamp")
        })
    except Exception as exc:
        return jsonify({"status": "error", "message": str(exc)}), 500


@bp.route("/disaster-data/flood/forecast", methods=["GET"])
def get_flood_forecast_endpoint():
    """Return official CWC Flood Forecast alongside Suraksha Kavach AI 14-day projection."""
    try:
        payload = FloodDataManager.get_live_flood_payload()
        ai_prediction = predict_flood(include_explanations=False)
        return jsonify({
            "status": "success",
            "officialCwcForecast": payload.get("cwcForecastOverview", {}),
            "surakshaKavachAiForecast": ai_prediction,
            "separationNotice": "Official CWC forecasts originate from Central Water Commission FFS. AI 14-day trajectories are model-generated by Suraksha Kavach."
        })
    except Exception as exc:
        return jsonify({"status": "error", "message": str(exc)}), 500


@bp.route("/predict/flood", methods=["GET"])
def predict_flood_endpoint():
    """AI/ML flood-risk prediction with calendar day/month/year/range query support."""
    from app.utils.disaster_analytics import DisasterAnalyticsManager
    target_date = request.args.get('date')
    target_month = request.args.get('month')
    target_year = request.args.get('year')
    start_date = request.args.get('from')
    end_date = request.args.get('to')

    if target_date:
        return jsonify(DisasterAnalyticsManager.predict_target_date('floods', target_date))
    elif target_month:
        return jsonify(DisasterAnalyticsManager.predict_target_month('floods', target_month))
    elif target_year:
        return jsonify(DisasterAnalyticsManager.predict_target_year('floods', target_year))
    elif start_date and end_date:
        return jsonify(DisasterAnalyticsManager.predict_custom_range('floods', start_date, end_date))

    try:
        return jsonify(predict_flood(include_explanations=True))
    except Exception as exc:
        return jsonify({"error": f"Flood prediction failed: {exc}"}), 500


@bp.route("/disaster-data/flood/refresh", methods=["POST"])
def refresh_flood_data():
    """Manual refresh trigger: re-sync all CWC/NWIC datasets and retrain AI models."""
    try:
        combined = FloodDataManager.get_live_flood_payload(force=True)
        from app.utils.flood_ml import train_flood_models
        meta = train_flood_models(force=True)
        return jsonify({
            "status": "success",
            "message": "Official CWC/NWIC flood telemetry refreshed and Suraksha Kavach AI models synced.",
            "classifier": meta.get("classifier_kind"),
            "discharge_model": meta.get("discharge_model_kind"),
            "trained_at": meta.get("trained_at"),
            "timestamps": combined.get("timestamps", {})
        })
    except Exception as exc:
        return jsonify({"status": "error", "message": str(exc)}), 500
